import java.nio.file.Paths
import org.gradle.internal.os.OperatingSystem

plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'org.telegram.lottie-meta'
    id 'idea'
}

idea {
    module {
        excludeDirs += [
            file('jni/third_party'),
            file('jni/ffmpeg'),
            file('jni/tlottie'),
            file('jni/boringssl'),
            file('jni/sqlite')
        ]
    }
}

def buildTimestamp = System.getenv('BUILD_TIMESTAMP') ?: '0'
def commitId = System.getenv('COMMIT_ID')
def verName = "${APP_VERSION_NAME}${commitId?.take(7) ? "-${commitId.take(7)}" : ''}"
def verCode = 1270

def officialVer = APP_VERSION_NAME
def officialCode = APP_VERSION_CODE

def keystorePwd = null
def alias = null
def pwd = null

Properties properties
def base64 = System.getenv('LOCAL_PROPERTIES')
if (base64 != null && !base64.isBlank()) {
    properties = new Properties()
    properties.load(new ByteArrayInputStream(Base64.decoder.decode(base64)))
} else if (project.rootProject.file('local.properties').exists()) {
    properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())
}

if (properties != null) {
    keystorePwd = properties.getProperty('KEYSTORE_PASS')
    alias = properties.getProperty('ALIAS_NAME')
    pwd = properties.getProperty('ALIAS_PASS')
}

keystorePwd = keystorePwd ?: System.getenv('KEYSTORE_PASS') ?: ''
alias = alias ?: System.getenv('ALIAS_NAME') ?: 'NPigramX'
pwd = pwd ?: System.getenv('ALIAS_PASS') ?: ''

def nativeTarget = System.getenv('NATIVE_TARGET') ?: ''

if (nativeTarget == 'SKIP') {
    tasks.configureEach { task ->
        if (
            task.name.toLowerCase().contains('cmake') ||
            task.name.toLowerCase().contains('jni') ||
            task.name.toLowerCase().contains('test')
        ) {
            task.enabled = false
        }
    }
}

android {
    defaultConfig.applicationId = APP_PACKAGE

    androidResources {
        localeFilters += [
                'en', 'ar', 'de', 'es', 'es-rES', 'fa-rIR', 'in-rID', 'it', 'it-rIT', 'ja-rJP', 'ko', 'nl', 'pl-rPL', 'pt-rBR', 'ru-rRU', 'tr-rTR', 'uk-rUA', 'vi-rVN', 'zh-rCN', 'zh-rTW'
        ]
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            excludes += [
                'META-INF/*.version',
                'META-INF/*.properties',
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE*',
                'META-INF/NOTICE*',
                'META-INF/*.txt',
                'META-INF/*.txtproptp',
                'META-INF/*.kotlin_module',
                'META-INF/proguard/*',
                'proto/**',
                'play-services-*.properties'
            ]
        }
    }

    splits {
        abi {
            enable = true
            reset()
            universalApk = false
            if (nativeTarget == 'universal') {
                universalApk = true
                include 'armeabi-v7a', 'arm64-v8a', 'x86_64'
            } else if (!nativeTarget.isBlank()) {
                include nativeTarget
            } else {
                include 'arm64-v8a', 'x86_64'
            }
        }
    }

    defaultConfig {
        versionName verName
        versionCode verCode

        // obtain your own keys at https://core.telegram.org/api/obtaining_api_id
        def appId = '24690244'
        def appHash = '4dd5591360de775be460f2ebecb3bf1c'

        if (properties != null) {
            appId = properties.getProperty('TELEGRAM_APP_ID') ?: System.getenv('TELEGRAM_APP_ID') ?: appId
            appHash = properties.getProperty('TELEGRAM_APP_HASH') ?: System.getenv('TELEGRAM_APP_HASH') ?: appHash
        }

        buildConfigField 'String', 'BUILD_VERSION_STRING', '"' + verName + '"'
        buildConfigField 'String', 'OFFICIAL_VERSION', '"' + officialVer + '"'
        buildConfigField 'int', 'OFFICIAL_VERSION_CODE', officialCode + ''
        buildConfigField 'int', 'APP_ID', appId
        buildConfigField 'String', 'APP_HASH', '"' + appHash + '"'
        buildConfigField 'long', 'BUILD_TIMESTAMP', buildTimestamp + 'L'

        externalNativeBuild {
            cmake {
                if (nativeTarget == 'universal') {
                    abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
                } else if (!nativeTarget.isBlank()) {
                    abiFilters nativeTarget
                } else {
                    abiFilters 'arm64-v8a', 'x86_64'
                }
                arguments '-DANDROID_STL=c++_static', '-DANDROID_PLATFORM=android-24', '-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON'
                System.getenv('PATH').split(File.pathSeparator).any { path ->
                    var file = Paths.get("${path}${File.separator}ccache${if (OperatingSystem.current().windows) ".exe" else ""}").toFile()
                    if (file.exists()) {
                        println("Using ccache ${file.getAbsolutePath()}")
                        arguments += "-DANDROID_CCACHE=${file.getAbsolutePath()}"
                        arguments += "-DCMAKE_C_COMPILER_LAUNCHER=${file.getAbsolutePath()}"
                        arguments += "-DCMAKE_CXX_COMPILER_LAUNCHER=${file.getAbsolutePath()}"
                        return true
                    }
                }
            }
        }

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ['room.schemaLocation': "$projectDir/schemas".toString()]
            }
        }
    }

    bundle {
        language {
            enableSplit = false
        }
    }

    externalNativeBuild {
        cmake {
            version = '3.31.6+'
            path = 'jni/CMakeLists.txt'
        }
    }

    def isSigningAvailable = keystorePwd && alias && pwd && !project.hasProperty('withoutSigning') && System.getenv('DEBUG_BUILD') == null
    if (isSigningAvailable) {
        signingConfigs {
            release {
                storeFile project.file('release.keystore')
                storePassword keystorePwd
                keyAlias alias
                keyPassword pwd
                enableV1Signing = false
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildTypes {
        debug {
            isDefault = true
            debuggable = true
            jniDebuggable = true
            if (isSigningAvailable) {
                signingConfig = signingConfigs.release
            }
        }

        staging {
            debuggable = false
            jniDebuggable = false
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            matchingFallbacks = ['release', 'staging', 'debug']
            if (isSigningAvailable) {
                signingConfig = signingConfigs.release
            } else {
                signingConfig = signingConfigs.debug
            }
        }

        release {
            debuggable = false
            jniDebuggable = false
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            matchingFallbacks = ['release', 'staging', 'debug']
            if (isSigningAvailable) {
                signingConfig = signingConfigs.release
            } else {
                signingConfig = signingConfigs.debug
            }
        }
    }

    sourceSets.main.jniLibs.srcDirs = ['./jni/']

    namespace = 'org.telegram.messenger'
}

androidComponents {
    onVariants(selector().all()) { variant ->
        variant.outputs.forEach { output ->
            String gramName = 'NagramZ'
            String first = String.format('%s-v%s(%s)', gramName, verName, verCode)
            output.outputFileName.set(
                output.outputFileName.get()
                    .replace('TMessagesProj', first)
                    .replace('-release', '')
                    .replace('-staging', '')
            )
        }
    }
}

configurations.configureEach {
    exclude group: 'androidx.recyclerview', module: 'recyclerview'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    // official
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.palette:palette-ktx:1.0.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.2'
    implementation 'androidx.dynamicanimation:dynamicanimation:1.0.0'
    implementation 'androidx.mediarouter:mediarouter:1.8.1'
    implementation 'com.google.zxing:core:3.5.4'
    implementation 'androidx.sharetarget:sharetarget:1.2.0'
    implementation 'androidx.interpolator:interpolator:1.0.0'
    implementation 'androidx.biometric:biometric:1.1.0'
    implementation 'androidx.car.app:app:1.7.0'
    implementation 'androidx.car.app:app-projected:1.7.0'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
    compileOnly 'org.checkerframework:checker-qual:2.5.2'
    compileOnly 'org.checkerframework:checker-compat-qual:2.5.0'
    implementation 'com.google.firebase:firebase-messaging:25.1.2'
    implementation 'com.google.firebase:firebase-crashlytics:20.1.0'
    implementation 'com.google.firebase:firebase-analytics:22.2.0'
    implementation 'com.google.android.gms:play-services-cast-framework:22.3.1'
    implementation 'com.google.android.gms:play-services-maps:20.0.0'
    implementation 'com.google.android.gms:play-services-auth:21.6.0'
    implementation 'com.google.android.gms:play-services-vision:20.1.3'
    implementation 'com.google.android.gms:play-services-wearable:20.0.1'
    implementation 'com.google.android.gms:play-services-location:21.4.0'
    implementation 'com.googlecode.mp4parser:isoparser:1.0.6'
    implementation 'com.google.mlkit:language-id:17.0.6'
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation ('com.google.guava:guava:33.6.0-android') {
        exclude group: 'com.google.code.findbugs', module: 'jsr305'
        exclude group: 'org.checkerframework', module: 'checker-compat-qual'
        exclude group: 'org.checkerframework', module: 'checker-qual'
        exclude group: 'com.google.errorprone', module: 'error_prone_annotations'
        exclude group: 'com.google.j2objc', module: 'j2objc-annotations'
        exclude group: 'org.codehaus.mojo', module: 'animal-sniffer-annotations'
    }
    implementation 'com.google.android.gms:play-services-mlkit-subject-segmentation:16.0.0-beta1'
    implementation 'com.google.android.gms:play-services-mlkit-image-labeling:16.0.8'
    implementation "androidx.credentials:credentials:1.6.0"
    implementation "androidx.credentials:credentials-play-services-auth:1.6.0"
    implementation "io.noties.markwon:core:4.6.2"
    implementation "io.noties.markwon:ext-strikethrough:4.6.2"
    implementation "io.noties.markwon:ext-tables:4.6.2"
    implementation "io.noties.markwon:html:4.6.2"
    implementation "io.noties.markwon:inline-parser:4.6.2"
    implementation "io.noties.markwon:ext-latex:4.6.2"
    // payment
    implementation('com.stripe:stripe-android:2.0.2') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    implementation 'com.android.billingclient:billing:8.2.1'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs_nio:2.1.5'

    // kotlin
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'
    // utilities
    implementation 'org.osmdroid:osmdroid-android:6.1.20'
    // network
    implementation 'com.squareup.okhttp3:okhttp:5.5.0'
    implementation 'dnsjava:dnsjava:3.6.5'
    // add for emoji
    implementation 'com.jaredrummler:truetypeparser-light:1.0.0'
    // add for UnifiedPush
    implementation 'org.unifiedpush.android:connector:3.3.4'
    // add for save deleted messages
    implementation 'androidx.room:room-runtime:2.8.4'
    annotationProcessor 'androidx.room:room-compiler:2.8.4'
    // add for keep formatting in translations
    implementation 'org.apache.commons:commons-text:1.15.0'
    // translator from nekogram
    implementation 'app.nekogram.translator:translator:1.6.1'
    // tcp2ws from Nullgram
    implementation project(':libs:tcp2ws')

    compileOnly fileTree('libs')
}
